[tool.poetry]
name = "stockhero"
version = "0.1.0"
description = ""
authors = ["ianycchen <161403000+ianycchen@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
